services:
  mc:
    env_file:
      - .env
    extends:
      service: mc
      file: "./mc/compose.yaml"
  ofelia:
    env_file:
      - .env
    extends:
      service: ofelia
      file: "./ofelia/compose.yaml"

configs:
  mc:
    name: mc
    file: "./mc/config.json"
  ofelia:
    name: ofelia
    file: "./ofelia/config.ini"

volumes:
  files:
    name: ${SUB}-files
    external: true
  logs:
    name: ${SUB}-logs
    external: true

networks:
  ingress:
    name: ingress
    driver: overlay
    attachable: true
    external: true
