name: files-backuper

services:
  mc:
    extends:
      service: mc
      file: "./mc/compose.yaml"
  ofelia:
    extends:
      service: ofelia
      file: "./ofelia/compose.yaml"

volumes:
  files:
    name: files
    external: true
