services:
  mc:
    extends:
      service: mc
      file: "./mc/compose.yaml"
  ofelia:
    extends:
      service: ofelia
      file: "./ofelia/compose.yaml"

configs:
  mc:
    name: mc
    file: "./mc/config.json"
  ofelia:
    name: ofelia
    file: "./ofelia/config.ini"

volumes:
  files:
    name: ${ROOT_PROJ}_files
    external: true
