services:
  ofelia:
    image: ${REGISTRY}/ofelia
    runtime: runc
    restart: always
    network_mode: host
    environment:
      TZ: "Asia/Tehran"
    configs:
      - source: ofelia
        target: /etc/ofelia/config.ini
    volumes:
      - type: bind
        read_only: true
        source: /var/run/docker.sock
        target: /var/run/docker.sock
