services:
  ofelia:
    image: reg.oncolog.ir/ofelia
    container_name: files-ofelia
    restart: always
    network_mode: host
    environment:
      TZ: "Asia/Tehran"
    volumes:
      "./config.ini:/etc/ofelia/config.ini"
      "/var/run/docker.sock:/var/run/docker.sock:ro"
