services:
  mc:
    image: ${REGISTRY}/mc
    runtime: runc
    restart: always
    container_name: mc-oncolog-files
    entrypoint: tail
    command: -f /dev/null
    configs:
      - source: mc
        target: /root/.mc/config.json
    network_mode: host
    volumes:
      - type: volume
        read_only: true
        source: files
        target: /var/files
