services:
  mc:
    image: reg.oncolog.ir/mc
    restart: always
    container_name: files-backuper
    entrypoint: /usr/bin/tail
    command: -f /dev/null
    network_mode: host
    volumes:
      - "./config.json:/root/.mc/config.json"
      - "files:/var/files:ro"
